export const POSTS_REQUEST = "POSTS_REQUEST"
export const POSTS_SUCCESS = "POSTS_SUCCESS"
export const POSTS_FAILURE = "POSTS_FAILURE"

export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST"
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS"
export const CREATE_POST_FAILURE = "CREATE_POST_FAILURE"

export const GET_POST_BY_ID_REQUEST = "GET_POST_BY_ID_REQUEST"
export const GET_POST_BY_ID_SUCCESS = "GET_POST_BY_ID_SUCCESS"
export const GET_POST_BY_ID_FAILURE = "GET_POST_BY_ID_FAILURE"

export const DELETE_POST_REQUEST = "DELETE_POST_REQUEST"
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS"
export const DELETE_POST_FAILURE = "DELETE_POST_FAILURE"

export const PATCH_POST_REQUEST = "PATCH_POST_REQUEST"
export const PATCH_POST_SUCCESS = "PATCH_POST_SUCCESS"
export const PATCH_POST_FAILURE = "PATCH_POST_FAILURE"

export const GET_COMMENTS_REQUEST = "GET_COMMENTS_REQUEST"
export const GET_COMMENTS_SUCCESS = "GET_COMMENTS_SUCCESS"
export const GET_COMMENTS_FAILURE = "GET_COMMENTS_FAILURE"

export const DELETE_COMMENT_REQUEST = "DELETE_COMMENT_REQUEST"
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS"
export const DELETE_COMMENT_FAILURE = "DELETE_COMMENT_FAILURE"

export const PATCH_COMMENT_REQUEST = "PATCH_COMMENT_REQUEST"
export const PATCH_COMMENT_SUCCESS = "PATCH_COMMENT_SUCCESS"
export const PATCH_COMMENT_FAILURE = "PATCH_COMMENT_FAILURE"

export const NEW_COMMENT_REQUEST = "NEW_COMMENT_REQUEST"
export const NEW_COMMENT_SUCCESS = "NEW_COMMENT_SUCCESS"
export const NEW_COMMENT_FAILURE = "NEW_COMMENT_FAILURE"